services:
  - type: web
    name: qa-evaluator-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        value: pcsk_5EggTn_SpTzoVsw4m6uJsxtz6XMkFpnkDNN9WRZJXSvKCNxSzxyBpvmbnvGNTLhrpp2FK7
      - key: PINECONE_INDEX
        value: qa-evaluator
      - key: PINECONE_DIMENSION
        value: "768"
      - key: MODEL
        value: llama-3.1-8b-instant
      - key: NODE_ENV
        value: production
      - key: LANGFUSE_SECRET_KEY
        value: sk-lf-51786a3f-6207-4834-add1-996719ffa69c
      - key: LANGFUSE_PUBLIC_KEY
        value: pk-lf-71f396b8-b7ce-49bf-afce-d546975afa51
      - key: LANGFUSE_BASE_URL
        value: https://cloud.langfuse.com
